process.env.MCE_TEST = 'test'
export * from './stdin'
export * from './stdout'
export * from './mce'
export * from './input'
export * from './packageJSON'
export * from './spawn'
export * from './tree-maker'
import './global.jest'