#!/usr/bin/env node
process.env.NODE_ENV = process.argv.indexOf('-p') > -1 || process.argv.indexOf('--production') > -1 ? 'production' : 'development';
if (__dirname.indexOf('Development') > -1) {
	require(`${__dirname}\\node_modules\\ts-node\\register`);
	require('./src/cli');
} else {
	require('./cli');
}
